language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
  - 5.0
before_script:
  - npm install
  - npm install standard -g
script:
  - npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
